export const LOGIN_CMS = "LOGIN_CMS";
export const ERROR_LOGIN_CMS = "ERROR_LOGIN_CMS";
export const INFOR_ADMIN = "INFOR_ADMIN";

// ForGor passWord
export const ERROR_FORGOT_PASSWORD = "ERROR_FORGOT_PASSWORD";
export const RESET_FORGOT_PASSWORD = "RESET_FORGOT_PASSWORD";

// Infor User
export const LOADING_INFOR_USER = "LOADING_INFOR_USER";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const ERROR_INFOR_USER = "ERROR_INFOR_USER";
export const RESET_INFOR_USER = "RESET_INFOR_USER";

// topic
export const LOADING_TOPIC = "LOADING_TOPIC";
export const LIST_TOPIC = "LIST_TOPIC";
export const LIST_TOPIC_BY_NEWS = "LIST_TOPIC_BY_NEWS";
export const CREATE_TOPIC = "CREATE_TOPIC";
export const GETBYID_TOPIC = "GETBYID_TOPIC";
export const DELETE_TOPIC = "DELETE_TOPIC";
export const UPDATE_TOPIC = "UPDATE_TOPIC";

// role
export const LOADING_ROLE = "LOADING_ROLE";
export const LIST_ROLE = "LIST_ROLE";
export const LIST_PERMISSION = "LIST_PERMISSION";
export const CREATE_ROLE = "CREATE_ROLE";
export const GET_PERMISSION_ROLE = "GET_PERMISSION_ROLE";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const LIST_ROLE_BY_TEACHER_STAFF = "LIST_ROLE_BY_TEACHER_STAFF";

// Training
export const LOADING_TRAINING = "LOADING_TRAINING";
export const LIST_TRAINING = "LIST_TRAINING";
export const LIST_TRAINING_TEACHER = "LIST_TRAINING_TEACHER";
export const CREATE_TRAINING = "CREATE_TRAINING";
export const UPDATE_TRAINING = "UPDATE_TRAINING";

// Teacher
export const LOADING_TEACHER = "LOADING_TEACHER";
export const LIST_TEACHER = "LIST_TEACHER";
export const UPDATE_STATUS_TEACHER = "UPDATE_STATUS_TEACHER";
export const CREATE_TEACHER = "CREATE_TEACHER";
export const INFOR_TEACHER_BY_ID = "INFOR_TEACHER_BY_ID";
export const LIST_TEACHER_BY_ID_CLASS = "LIST_TEACHER_BY_ID_CLASS";
export const UPDATE_TEACHER = "UPDATE_TEACHER";

// Staff
export const LOADING_STAFF = "LOADING_STAFF";
export const LIST_STAFF = "LIST_STAFF";
export const CREATE_STAFF = "CREATE_STAFF";
export const UPDATE_STATUS_STAFF = "UPDATE_STATUS_STAFF";
export const INFOR_STAFF_BYID = "INFOR_STAFF_BYID";
export const UPDATE_STAFF = "UPDATE_STAFF";

// News
export const LOADING_NEW = "LOADING_NEW";
export const LIST_NEWS = "LIST_NEWS";
export const INFOR_NEWS_BY_ID = "INFOR_NEWS_BY_ID";
export const CREATE_NEWS = "CREATE_NEWS";
export const UPDATE_NEWS = "UPDATE_NEWS";
export const DELETE_NEWS = "DELETE_NEWS";

// Infor Training
export const LOADING_INFOR_TRAINING = "LOADING_INFOR_TRAINING";
export const LIST_INFOR_TRAINING = "LIST_INFOR_TRAINING";
export const CREATE_INFOR_TRAINING = "CREATE_INFOR_TRAINING";
export const GET_INFOR_TRAINING_BY_ID = "GET_INFOR_TRAINING_BY_ID";
export const UPDATE_INFOR_TRAINING = "UPDATE_INFOR_TRAINING";

// Courses
export const LOADING_COURSES = "LOADING_COURSES";
export const LIST_COURSES = "LIST_COURSES";
export const LIST_COURSES_NO_PERMISSION = "LIST_COURSES_NO_PERMISSION";
export const CREATE_COURSES = "CREATE_COURSES";
export const UPDATE_STATUS_COURSES = "UPDATE_STATUS_COURSES";
export const GET_COURSES_BY_ID = "GET_COURSES_BY_ID";
export const UPDATE_COURSES = "UPDATE_COURSES";

// Logs
export const LOADING_LOGS = "LOADING_LOGS";
export const LIST_LOGS = "LIST_LOGS";

// Class
export const LOADING_CLASS = "LOADING_CLASS";
export const LIST_CLASSALL = "LIST_CLASSALL";
export const UPDATE_STATUS_CLASSALL = "UPDATE_STATUS_CLASSALL";
export const ADD_TIME_DAY_BY_WEEK = "ADD_TIME_DAY_BY_WEEK";
export const CREATE_CLASSALL = "CREATE_CLASSALL";
export const DELETE_DAY_BY_WEEK = "DELETE_DAY_BY_WEEK";
export const DELETE_All_DAY_BY_WEEK = "DELETE_All_DAY_BY_WEEK";
export const INFOR_CLASS_All_BY_ID = "INFOR_CLASS_All_BY_ID";
export const RESET_STORE_CLASSALL = "RESET_STORE_CLASSALL";
export const UPDATE_CLASSALL = "UPDATE_CLASSALL";
export const LIST_CLASS_NO_PERMISSION = "LIST_CLASS_NO_PERMISSION";
export const GET_LIST_CLASS_BYID_TEACHER = "GET_LIST_CLASS_BYID_TEACHER";
export const ERROR_CLASS = "ERROR_CLASS";
export const LIST_STUDENT_BYID_CLASS = "LIST_STUDENT_BYID_CLASS";
export const INFOR_STUDENT_CLASS = "INFOR_STUDENT_CLASS";
export const STATISTIC_BYID_CLASS = "STATISTIC_BYID_CLASS";
export const STATISTIC_CLASS_ALL = "STATISTIC_CLASS_ALL";

// student Register
export const LOADING_STUDENT_REGISTER = "LOADING_STUDENT_REGISTER";
export const LIST_STUDENT_REGISTER_LEARN = "LIST_STUDENT_REGISTER_LEARN";
export const GET_STUDENT_REGISTER_BY_ID = "GET_STUDENT_REGISTER_BY_ID";
export const GET_INFOR_TUITION_BY_ID_CLASS = "GET_INFOR_TUITION_BY_ID_CLASS";
export const STATISTIC_REGIS = "STATISTIC_REGIS";
export const STATISTIC_REGIS_PAYMENT = "STATISTIC_REGIS_PAYMENT";

// student
export const LOADING_STUDENT = "LOADING_STUDENT";
export const LIST_STUDENT = "LIST_STUDENT";
export const GET_STUDENT_BY_ID = "GET_STUDENT_BY_ID";
export const GET_CLASS_STUDENT = "GET_CLASS_STUDENT";

// Score Cumulative
export const LOADING_SCORE_CUMULATIVE = "LOADING_SCORE_CUMULATIVE";
export const LIST_SCORE_CUMULATIVE = "LIST_SCORE_CUMULATIVE";
export const GET_SCORE_CUMULATIVE_BY_ID = "GET_SCORE_CUMULATIVE_BY_ID";
export const LIST_AFF_BY_ID = "LIST_AFF_BY_ID";

// Statistic
export const LOADING_STATISTIC = "LOADING_STATISTIC";
export const GET_STATISTIC_BY_YEAR = "GET_STATISTIC_BY_YEAR";
export const GET_STATISTIC_BY_MONTH = "GET_STATISTIC_BY_MONTH";
export const GET_TOTAL_STATISTIC = "GET_TOTAL_STATISTIC";
export const GET_STATISTIC_BY_DATE = "GET_STATISTIC_BY_DATE";
export const ERROR_STATISTIC = "ERROR_STATISTIC";
export const RESET_STATISTIC = "RESET_STATISTIC";

// Noti
export const LOADING_NOTI = "LOADING_NOTI";
export const GET_LIST_NOTI = "GET_LIST_NOTI";
export const ERROR_NOTI = "ERROR_NOTI";

// diploma
export const LOADING_DIPLOMA = "LOADING_DIPLOMA";
export const GET_LIST_DIPLOMA = "GET_LIST_DIPLOMA";
export const GET_DIPLOMA_BY_ID = "GET_DIPLOMA_BY_ID";

// Pay
export const LOADING_PAY = "LOADING_PAY";
export const GET_LIST_PAY = "GET_LIST_PAY";
export const GET_PAY_BY_ID = "GET_PAY_BY_ID";

// Carousel
export const LOADING_CAROUSEL = "LOADING_CAROUSEL";
export const GET_LIST_CAROUSEL = "GET_LIST_CAROUSEL";

// Perceptions
export const LOADING_PERCEPTIONS = "LOADING_PERCEPTIONS";
export const GET_LIST_PERCEPTIONS = "GET_LIST_PERCEPTIONS";
export const GET_PERCEPTIONS_BY_ID = "GET_PERCEPTIONS_BY_ID";

// Intrduction And Contact
export const LOADING_INTRO_CONTACT = "LOADING_INTRO_CONTACT";
export const GET_LIST_INTRO_CONTACT= "GET_LIST_INTRO_CONTACT";
export const GET_INTRO_CONTACT_BY_ID = "GET_INTRO_CONTACT_BY_ID";
