// Training
export const LOADING_TRAINING = "LOADING_TRAINING";
export const LIST_TRAINING = "LIST_TRAINING";
export const LIST_TRAINING_BY_ID = "LIST_TRAINING_BY_ID";
export const ERROR_TRAINING = "ERROR_TRAINING";

// News
export const LOADING_NEWS = "LOADING_NEWS";
export const LIST_NEWS = "LIST_NEWS";
export const LIST_NEWS_BYIY_TOPIC = "LIST_NEWS_BYIY_TOPIC";
export const NEWS_BYIY = "NEWS_BYIY";
export const LIST_NEWS_HOME = "LIST_NEWS_HOME";
export const ERROR_NEWS = "ERROR_NEWS";

// Teacher
export const LOADING_TEACHER = "LOADING_TEACHER";
export const LIST_TEACHER = "LIST_TEACHER";
export const TEACHER_BY_ID = "TEACHER_BY_ID";
export const ERROR_TEACHER = "ERROR_TEACHER";

// Topic
export const LOADING_TOPIC = "LOADING_TOPIC";
export const LIST_TOPIC = "LIST_TOPIC";
export const ERROR_TOPIC = "ERROR_TOPIC";

// InforTraining
export const LOADING_INFORTRAINING = "LOADING_INFORTRAINING";
export const LIST_INFORTRAINING = "LIST_INFORTRAINING";
export const GET_BYID_INFORTRAINING = "GET_BYID_INFORTRAINING";
export const ERROR_INFORTRAINING = "ERROR_INFORTRAINING";

// Courese
export const LOADING_COURSES = "LOADING_COURSES";
export const LIST_COURSES = "LIST_COURSES";
export const ERROR_COURSES = "ERROR_COURSES";

// RegisterCourese
export const LOADING_REGISTER_COURSES = "LOADING_REGISTER_COURSES";
export const LIST_REGISTER_COURSES = "LIST_REGISTER_COURSES";
export const ERROR_REGISTER_COURSES = "ERROR_REGISTER_COURSES";
export const RESET_REGISTER_COURSES = "RESET_REGISTER_COURSES";
// -- load page payment
export const LOAD_PAGE_PAYMENT = "LOAD_PAGE_PAYMENT";
export const LOAD_BUTTON_REGISTER = "LOAD_BUTTON_REGISTER";

// Diploma
export const LOADING_DIPLOMA = "LOADING_DIPLOMA";
export const LIST_DIPLOMA = "LIST_DIPLOMA";
export const ERROR_DIPLOMA = "ERROR_DIPLOMA";
export const RESET_DIPLOMA = "RESET_DIPLOMA";

// -- Page payment
export const LOADING_PAGE_PAYMENT = "LOADING_PAGE_PAYMENT";
export const RESULT_DATA_PAYMENT = "RESULT_DATA_PAYMENT";
export const RESET_CHECKOUT_PAYMENT = "RESET_CHECKOUT_PAYMENT";

//-- Covid 19
export const LOADING_COVID19 = "LOADING_COVID19";
export const DATA_COVID19_VI = "DATA_COVID19_VI";
export const DATA_COVID19_WD = "DATA_COVID19_WD";
export const ERROR_COVID19 = "ERROR_COVID19";

//-- Carousel
export const LOADING_CAROUSEL = "LOADING_CAROUSEL";
export const GET_LIST_CAROUSEL = "GET_LIST_CAROUSEL";
export const ERROR_CAROUSEL = "ERROR_CAROUSEL";

//-- Carousel
export const LOADING_PERCEPTIONS = "LOADING_PERCEPTIONS";
export const GET_LIST_PERCEPTIONS = "GET_LIST_PERCEPTIONS";
export const ERROR_PERCEPTIONS = "ERROR_PERCEPTIONS";

// Intrduction And Contact
export const LOADING_INTRO_CONTACT = "LOADING_INTRO_CONTACT";
export const GET_LIST_INTRO_CONTACT = "GET_LIST_INTRO_CONTACT";
